### ISSUE TITLE
Porting from C, gotchas

### ISSUE THREAD

**Issue by p0nce** [p0nce/d-idioms#1]

**Comment by p0nce** [comment]
- `c_long`, `c_ulong` DONE
- static arrays in function signatures DONE
- enum values without namespacing DONE
- replacing array to pointer implicit conversion by `.ptr` DONE

**Comment by aldanor** [comment]
Off top of my head:
- anonymous nested structs DONE
- pragma(mangle) DONE
- global C variables (extern __gshared) DONE

**Comment by p0nce** [comment]
How do you solve anonymous nested structs?
When do you use pragma(mangle)?

**Comment by aldanor** [comment]
`pragma(mangle)` is extremely useful when you need to access a C function whose name is a reserved D keyword, e.g.:

``` d
pragma(mangle, "version") extern(C) void c_version();
```

Anonymous structs (this one might be obvious) in C:

``` c
struct Foo {
    struct {
        int x;
    } bar;
};
```

would have to be declared as

``` d
struct Foo {
    private struct bar_t {
        int x;
    }
    bar_t bar;
}
```

**Comment by p0nce** [comment]
OK. I woudln't have thought of the `private` for anonymous struct.

I think I'll split explicitely "bindings with C" and "porting from C" tips (tips that can be applied with static/dynamic bindings and translating, not just static bindings).

**Comment by p0nce** [comment]
http://p0nce.github.io/d-idioms/#Linking-with-C-gotchas
http://p0nce.github.io/d-idioms/#Porting-from-C-gotchas
