### ISSUE TITLE
Anonymoust structs actually exist in D

### ISSUE THREAD

**Issue by p0nce** [p0nce/d-idioms#10]
http://forum.dlang.org/post/rgrqdivmhdkkvfepadyc@forum.dlang.org

**Comment by p0nce** [comment]
So...

``` d
struct S
{
    struct
    {
        int foo;
    } bar;
}
```

doesn't work but

``` d
struct S
{
    struct
    {
        int foo;
    }
}
```

work. That doesn't allow to translate an anonymous C struct member like:

``` c
struct S
{
    struct
    {
        int foo;
    } bar;
};
```

**Comment by joakim-noah** [comment]
Yes, you're right that D doesn't allow declaring an anonymous struct as a variable right away, ["D does not support declaring variables of anonymous struct types. In such a case you can define a named struct in D and make it private"](http://dlang.org/interfaceToC.html), so the example you gave in your list is fine.  But D does support nested anonymous structs/unions generally, so your explanation that it doesn't have them at all is wrong.  For example, [there are many nested anonymous unions in druntime](https://github.com/D-Programming-Language/druntime/blob/master/src/core/sys/posix/signal.d#L428).

**Comment by p0nce** [comment]
I see. Fixed wording.
