### ISSUE TITLE
debug assert(...) can be used in @nogc code

### ISSUE THREAD

**Issue by aferust** [p0nce/d-idioms#175]
Yes. even exceptions can be thrown.

@nogc nothrow:

...
debug throw new Exception("Stuff"); // Of course only for debug builds.
...

This feature is always forgotten (me included).

**Comment by p0nce** [comment]
It is said in https://p0nce.github.io/d-idioms/#So-what-does--debug-do,-exactly?

**Comment by p0nce** [comment]
Note that it's not clear in the community the consequence of breaking the type system like this. It's kind of UB
