### ISSUE TITLE
How to install D Langage on Windows 10

### ISSUE THREAD

**Issue by rstephane** [p0nce/d-idioms#177]
here is a D-idiom PDF & Mardown file about "How to install D Langage on Windows 10":

[Installing_Dlang_Windows_10.pdf](https://github.com/p0nce/d-idioms/files/8487811/Installing_Dlang_Windows_10.pdf)

[Installing_Dlang_Windows_10.md](https://github.com/p0nce/d-idioms/files/8487812/Installing_Dlang_Windows_10.md)

**Comment by p0nce** [comment]
Also need thids Dplug wiki change:

> now, could you change for me the Getting_started page, 
> just after this section, at the beginning of the getting_started wiki page: 

add

> For more details on installing D language on Microsoft Windows 10, you can check [this dedicated page](https:// d-idioms ... 
> how to install URL).
> In case you encounter an issue while installing D language, post your questions on the D.learn forum : 
> https://forum.dlang.org/group/learn

**Comment by p0nce** [comment]
Done.
