### ISSUE TITLE
Question about unregistered threads

### ISSUE THREAD

**Issue by AndrejMitrovic** [p0nce/d-idioms#180]
Hey @p0nce!

I've got a question about https://p0nce.github.io/d-idioms/#The-impossible-real-time-thread

> Another limitation: Such a thread must not hold roots to GC objects. What it means is that you can use GC objects from the real-time thread, but these GC objects should be pointed to by registered threads to avoid them being collected.

Isn't there a risk that a registered thread's GC ends up re-allocating objects and dynamic arrays (e.g. buffers) to avoid memory fragmentation? In that case the non-registered thread may end up with dangling pointers to those objects / buffers right?

**Comment by p0nce** [comment]
Do we have such a moving GC in D?

**Comment by AndrejMitrovic** [comment]
I think that's the only thing preventing things from breaking today, that the GC is still not moving.

I guess it won't be a problem if we make the moving optional (perhaps a runtime GC switch).

**Comment by AndrejMitrovic** [comment]
It looks like we can manually force the GC to avoid moving particular bits of memory: https://dlang.org/phobos/core_memory.html#NO_MOVE

**Comment by AndrejMitrovic** [comment]
Oh and there's a nice example of using it here: https://dlang.org/library/core/memory/gc.add_root.html

So it looks like that answers my questions. Maybe this could be added to the idioms page? Up to you~

**Comment by p0nce** [comment]
Can't do this these times.
