### ISSUE TITLE
remove element from dynamic array

### ISSUE THREAD

**Issue by extrawurst** [p0nce/d-idioms#31]
If i am not the only one who needs to look up this pattern everytime again this idiom maybe useful for others:

```
auto removeElement(R,N)(R _haystack, N _needle){
    import std.algorithm:countUntil,remove;

    auto index = _haystack.countUntil(_needle);

    return (index != -1) ? _haystack.remove(index) : _haystack;
}
```

usage:

```
auto arr = [1,5,10];
arr = arr.removeElement(5);
assert(arr == [1,10]);
```

**Comment by p0nce** [comment]
Good idea. I simply didn't know how to do it.

**Comment by p0nce** [comment]
Do you have a code example for an associative array too?

**Comment by extrawurst** [comment]
A associative array has a remove method builtin: http://dlang.org/hash-map.html

```
int[string] foo;
foo.remove("bar");
```

**Comment by p0nce** [comment]
I'll do an item with everything related to adding/removing from arrays.
- Appending an element to a dynamic array
- Inserting an element into a dynamic array
- Removing an element from a dynamic array given an index
- Removing an element from a dynamic array given a value
- Adding an element into an associate array
- Removing an element from an associate array given a key

**Comment by p0nce** [comment]
http://p0nce.github.io/d-idioms/#Adding-or-removing-an-element-from-an-array

**Comment by extrawurst** [comment]
great! although i wonder why phobos doesn't make it easier to remove an element, maybe the above should be included into std.algo

**Comment by p0nce** [comment]
Well it does provide remove with a predicate which is range-friendly and can implement your function.
`remove!("a == value")(arr)`

**Comment by extrawurst** [comment]
your example does not work for me:

```

auto rm(R,N)(R heystack, N needle){
    import std.algorithm;
    return heystack.remove!"a == needle"();
}

void main(string[ ] args){
   auto arr = [1,5,10];

   arr = arr.rm(5);

   assert(arr == [1,10]);
}
```

this gives:

```
/usr/include/dmd/phobos/std/functional.d-mixin-49(49): Error: undefined identifier needle                                                                       
/usr/include/dmd/phobos/std/algorithm.d(8782): Error: template instance std.functional.unaryFun!("a == needle", "a").unaryFun!int error instantiating           
main.d(6):        instantiated from here: remove!("a == needle", cast(SwapStrategy)2, int[])                                                                    
main.d(13):        instantiated from here: rm!(int[], int)     
```
