### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by dmi7ry** [p0nce/d-idioms#32]
> ..d-idioms> dub
> Building dmarkdown 0.2.0 configuration "library", build type debug.
> Running dmd...
> C:\Users\Dmitry\AppData\Roaming\dub\packages\dmarkdown-.2.0\source\dmarkdown\markdown.d(275): Error: no property 'joiner' for type 'Take!(Repeat!string)'
> C:\Users\Dmitry\AppData\Roaming\dub\packages\dmarkdown-.2.0\source\dmarkdown\markdown.d(278): Error: no property 'map' for type 'Block[]'
> FAIL C:\Users\Dmitry\AppData\Roaming\dub\packages\dmarkdown-0.2.0.dub\build\library-debug-windows-x86-dmd_2067-1564E97DABD8A03ACA3F1B08A8738B6E\ dmarkdown staticLibrary
> Error executing command run: dmd failed with exit code 1.

**Comment by p0nce** [comment]
Is it with DMD 2.067?

**Comment by dmi7ry** [comment]
Yes

**Comment by p0nce** [comment]
Since you are using the latest dmarkdown version (v0.2.0) I would suggest to open a bug on https://github.com/kiith-sa/dmarkdown/

Once the new fixed version is commited and registered on code.dlang.org, clear your DUB cache and dub.selections.json and the latest tag should be taken.

**Comment by dmi7ry** [comment]
I'm nothing using :) It's dub :)
Ok, I understand. Thank you for d-idioms!

**Comment by p0nce** [comment]
Let me explain : the problem is that dmarkdown should know that their version break with the latest DMD. There is nothing to change in d-idioms specifically :)

**Comment by dmi7ry** [comment]
Yes, I understand it. I already created the issue http://github.com/kiith-sa/dmarkdown/issues/5
