### ISSUE TITLE
hack to override onInvalidMemoryOperationError

### ISSUE THREAD

**Issue by extrawurst** [p0nce/d-idioms#40]
this is too weird and useful to go down unnoticed: http://forum.dlang.org/thread/joefjvuxpvwsfozvykgu@forum.dlang.org#post-kwggroyzniavchsdqtka:40forum.dlang.org

**Comment by p0nce** [comment]
I've read it but didn't understand it. Does it redefine the `onInvalidMemoryOperationError` in druntime?

**Comment by extrawurst** [comment]
no at link time since the linker seems to favor objects in the .o over the .lib files

**Comment by p0nce** [comment]
A bit too platform specific for being in d-idioms, this isn't really a language thing.
