### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by WebFreak001** [p0nce/d-idioms#74]
When a process spawned by std.process stops its still active as unkillable zombie process because the OS thinks the application might still need the data from it.

To stop them from happening you should always call pid.wait() when the process isn't used anymore. Scope guards are also great for this.

**Comment by p0nce** [comment]
Not language specific, but that would make a good title.
Do you think this error is easy to get ?

**Comment by WebFreak001** [comment]
Every time you start a process using std.process this will happen, so if you have a program that starts a program very often (for example DCD) then it can pretty quickly spam processes if not properly closed

**Comment by p0nce** [comment]
Never had the problem. The documentation for std.process says to call wait(). I'm not sure it fits d-idioms theme. This is a bit of the same things with every process or thread API.
But if someone else finds this confusing, sure.
