### ISSUE TITLE
Potential problem in GC-proof resource class article

### ISSUE THREAD

**Issue by jpf91** [p0nce/d-idioms#92]
The solution mentioned in the article is supposed to work with `object.destroy`. However, it doesn't explain that `object.destroy` reinitializes the class (overwrites contents with `.init`).

So the comment:

``` d
        // Such a destructor must support repeated calls for
        // the case when it is first called by destroy() and
        // then called by the GC later
        if (handle != null)
        [...]
        handle = null;
```

is correct, but I think it needs to be stressed that the destructor call by the GC will see the class `.init` value, not the value set in the destructor. So users actually have to check against the value used to initialize the field.

Additionally, I can't even get the GC to call the destructor after a `destroy` call. The [druntime code](https://github.com/D-Programming-Language/druntime/blob/master/src/rt/lifetime.d#L1352) is cryptic, but it seems that the code checks a hidden field in the class before calling the destructor. And this field seems to be set to null when the initializer is copied into the object:
http://dpaste.dzfl.pl/4199205f4fee

**Comment by p0nce** [comment]
I always had a doubt about repeated calls actually. 
You found that it is probably impossible. Makes much more sense that way, I also never got a destructor called multiple times when trying.
That will make the idiom less ugly to use in practice.

**Comment by p0nce** [comment]
6bb4d8c7e00bf2201f423ef3ffe9b03411b862c3

**Comment by jpf91** [comment]
Thanks!

>  That will make the idiom less ugly to use in practice.

I guess it's time to get rid of all these `dispose` methods in D projects ;-)

**Comment by p0nce** [comment]
Absolutely. I've pushed for wrong solutions for years :)
Use the regular destructor, and use `.destroy()`
